# Use when EasyPanel Build Path = /frontend
services:
  layalibeauty-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      HOSTNAME: '0.0.0.0'
      NODE_ENV: production
    restart: unless-stopped
