import type { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: 'layali-eye-001',
    slug: 'bilberry-grape-gummies',
    sku: 'LB-EYE-001',
    name: 'علكات التوت البري وبذور العنب ضد الهالات السوداء',
    shortName: 'علكات العين',
    routineNameLocal: 'روتين العين',
    routineNameEnglish: 'Eye Routine',
    category: 'eye-care',
    format: 'gummies',
    problem: 'الهالات السوداء وتعب تحت العين',
    mainIngredient: 'توت بري وبذور عنب',
    cardHeadline: 'علكات سريرية ضد الهالات',
    cardSubheadline: 'تستهدف الأوعية الضعيفة تحت العين بجرعة سريرية يومية',
    rating: 4.9,
    reviewsCount: 312,
    priceFrom: 79,
    imageUrl: '',
    imageAlt: 'علكات التوت البري وبذور العنب',
    badgeText: 'Layali Eye',
  },
  {
    id: 'layali-youth-001',
    slug: 'astaxanthin-gummies',
    sku: 'LB-YOUTH-001',
    name: 'علكات الأستازانثين ضد التجاعيد',
    shortName: 'علكات الشباب',
    routineNameLocal: 'روتين الشباب',
    routineNameEnglish: 'Youth Routine',
    category: 'anti-aging',
    format: 'gummies',
    problem: 'التجاعيد وخطوط التعب المبكرة',
    mainIngredient: 'أستازانثين وريسفيراترول',
    cardHeadline: 'مضادات أكسدة قوية ضد الشيخوخة',
    cardSubheadline: 'تركيبة سريرية لدعم مرونة البشرة من الداخل',
    rating: 4.8,
    reviewsCount: 401,
    priceFrom: 89,
    imageUrl: '',
    imageAlt: 'علكات الأستازانثين',
    badgeText: 'Layali Youth',
  },
  {
    id: 'layali-glow-001',
    slug: 'glutathione-collagen-gummies',
    sku: 'LB-GLOW-001',
    name: 'علكات الجلوتاثيون والكولاجين ضد الشيخوخة',
    shortName: 'علكات الإشراق',
    routineNameLocal: 'روتين الإشراق',
    routineNameEnglish: 'Glow Routine',
    category: 'skin-brightening',
    format: 'gummies',
    problem: 'بهتان البشرة وفقدان المرونة',
    mainIngredient: 'جلوتاثيون وكولاجين',
    cardHeadline: 'إشراقة ومرونة من الداخل',
    cardSubheadline: 'دعم مضاد للأكسدة مع كولاجين مُهضَم لبشرة أكثر حيوية',
    rating: 4.9,
    reviewsCount: 287,
    priceFrom: 99,
    imageUrl: '',
    imageAlt: 'علكات الجلوتاثيون والكولاجين',
    badgeText: 'Layali Glow',
  },
];
